minimum_pre_commit_version: 2.15.0
ci:
  autofix_prs: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: e05c5c0818279e5ac248ac9e954431ba58865e61  # frozen: v0.15.7
    hooks:
      - id: ruff-check
        args:
          - --fix
      - id: ruff-format
