name: CI

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - master

env:
  PIP_DISABLE_PIP_VERSION_CHECK: '1'

jobs:

  Test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          # With the Redis client
          - { python-version: '3.10', install-extra: '[redis]' }
          - { python-version: '3.11', install-extra: '[redis]' }
          - { python-version: '3.12', install-extra: '[redis]' }
          - { python-version: '3.13', install-extra: '[redis]' }
          - { python-version: '3.13', install-extra: '[redis,sentry]'}
          - { python-version: '3.13', install-extra: '[redis,sentry,orjson]'}
          # With the Valkey server
          - { python-version: '3.13', install-extra: '[redis]', redis-image: 'valkey/valkey:8'}
          # With the Valkey client and Valkey server
          - { python-version: '3.13', install-extra: '[valkey,sentry]', redis-image: 'valkey/valkey:8'}
    services:
      redis:
        image: ${{ matrix.redis-image || 'redis' }}
        ports:
          - 6379:6379
    env:
      REDIS_URL: 'redis://localhost:6379/0'
      SENTRY_DSN: 'http://user:pass@localhost:12340/foo'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          python-version: '${{ matrix.python-version }}'
          activate-environment: true
      - run: 'uv pip install -e ".$EXTRA"'
        env:
          EXTRA: '${{ matrix.install-extra }}'
      - run: uv run pytest -vvv --cov .
      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          name: 'Python ${{ matrix.python-version }}'

  Lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          cache-dependency-glob: ".github/workflows/*.yml"
          cache-suffix: pre-commit-uv
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-uv-v1-${{ hashFiles('.pre-commit-config.yaml') }}
      - run: uvx --with=pre-commit-uv pre-commit run --all-files --show-diff-on-failure --color=always

  Mypy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          python-version: '3.13'
          activate-environment: 'true'
      # `mypy` requires `pip` to install types...
      - run: uv run --with=pip --all-extras mypy --strict --install-types --non-interactive --show-error-codes minique

  Build:
    runs-on: ubuntu-24.04
    needs: [ Lint, Mypy, Test ]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          python-version: '3.13'
      - run: uv build
      - run: uvx twine check dist/*
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: build
          path: dist
      - name: Publish distribution to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2
        with:
          print_hash: true
          password: ${{ secrets.PYPI_API_TOKEN }}
